java:
  runtime:
    version: 11
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://192.168.10.100:5432/burnhop"
    username: postgres
    password: admin

#Swagger Configurations

server:
  port: ${PORT:9000}
