DROP TABLE IF EXISTS login;
DROP TABLE IF EXISTS users;

CREATE TABLE login ( id INTEGER PRIMARY KEY, email VARCHAR ( 100 ) NOT NULL UNIQUE, password VARCHAR ( 200 ) NOT NULL);
CREATE TABLE users 
	( 
	id INTEGER PRIMARY KEY, 
	name VARCHAR ( 70 ) NOT NULL, 
	username VARCHAR ( 20 ), 
	data_nasc DATE UNIQUE NOT NULL,
	created_on TIMESTAMP NOT NULL, 
	login_id INTEGER NOT NULL,
	FOREIGN KEY(login_id) REFERENCES login(id)
 );
